# Gemfile
source "https://rubygems.org"

# Web framework
gem "sinatra", "~> 3.2"

# Ekstra Sinatra-helpers (fx sinatra/json)
gem "sinatra-contrib", "~> 3.2"

# Flash messages
gem "sinatra-flash", "~> 0.3.0"

# Webserver
gem "puma", "~> 6.0"

# Database
gem "sqlite3", "1.6.9"

# Password hashing
gem "bcrypt", "~> 3.1"

# In order to use secrets from .env file
gem "dotenv", "~> 3.1"


# YAML er en del af Ruby stdlib, så den behøves ikke at tilføjes som gem

gem 'httparty'


group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'selenium-webdriver'
end