# Gemfile
source 'https://rubygems.org'

# Web framework
gem 'sinatra', '~> 3.2'

# Ekstra Sinatra-helpers (fx sinatra/json)
gem 'sinatra-contrib', '~> 3.2'

# Flash messages
gem 'sinatra-flash', '~> 0.3.0'

# Webserver
gem 'puma', '~> 7.1'

# Database
gem 'pg'
gem 'sequel'
gem 'sqlite3', '~> 1.7'

# Password hashing
gem 'bcrypt', '~> 3.1'

# In order to use secrets from .env file
gem 'dotenv', '~> 3.1'

# YAML er en del af Ruby stdlib, så den behøves ikke at tilføje som gem

gem 'httparty'
gem 'nokogiri'
gem 'rake'

group :test do
  gem 'capybara'
  gem 'rspec'
  gem 'selenium-webdriver'
end
# Prometheus til monitorering
gem 'prometheus-client'
# Gemfile
source 'https://rubygems.org'

group :development, :test do
  gem 'rubocop', require: false
  gem 'rubocop-minitest', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
end
