require 'nokogiri'
require 'open-uri'
require 'sqlite3'

# Prevent Sinatra from starting the web server when required
require 'sinatra'
set :run, false

require './app'

desc "Scrape new sites and add to search engine"
task :scrape_sites do
  puts "Starting scrape..."

  # List of URLs to scrape based on user search trends
  urls_to_scrape = [
    'https://en.wikipedia.org/wiki/Unsupervised_learning',
    'https://developer.mozilla.org/en-US/', # Web development
    'https://www.python.org/',
    'https://www.rust-lang.org/',
    'https://en.wikipedia.org/wiki/Forth_(programming_language)',
    'https://en.wikipedia.org/wiki/Assembly_language',
    'https://docs.microsoft.com/en-us/dotnet/csharp/',
    'https://www.adaic.org/',
    'https://coq.inria.fr/',
    'https://www.php.net/',
    'https://en.wikipedia.org/wiki/Distributed_database',
    'https://en.wikipedia.org/wiki/Modula-2',
    'https://en.wikipedia.org/wiki/Machine_learning',
    'https://dart.dev/',
    'https://www.arangodb.com/',
    'https://hadoop.apache.org/',
    'https://www.lua.org/',
    'https://www.gnu.org/software/bash/',
    'https://www.ruby-lang.org/en/',
    'https://julialang.org/',
    'https://common-lisp.net/',
    'https://crystal-lang.org/',
    'https://en.wikipedia.org/wiki/Internet_of_things',
    'https://fsharp.org/',
    'https://www.r-project.org/',
    'https://seed7.sourceforge.net/',
    'https://go.dev/',
    'https://www.swift.org/',
    'https://kotlinlang.org/',
    'https://elixir-lang.org/',
    'https://www.haskell.org/',
    'https://ocaml.org/',
    'https://www.perl.org/',
    'https://en.wikipedia.org/wiki/SQL',
    'https://www.docker.com/',
    'https://kubernetes.io/',
    'https://www.mongodb.com/',
    'https://react.dev/',
    'https://vuejs.org/',
    'https://angular.io/',
    'https://nodejs.org/',
    'https://unicon.org/',
    'https://en.wikipedia.org/wiki/Parallel_computing',
    'https://arc-language.github.io/',
    'https://mozart.github.io/', # Oz
    'https://en.wikipedia.org/wiki/Penetration_test',
    'https://en.wikipedia.org/wiki/Database_normalization',
    'https://en.wikipedia.org/wiki/IBM_RPG',
    'https://en.wikipedia.org/wiki/Data_science',
    'https://en.wikipedia.org/wiki/Virtual_reality',
    'https://learn.microsoft.com/en-us/office/vba/api/overview/',
    'https://opendylan.org/',
    'https://www.snobol4.org/',
    'https://en.wikipedia.org/wiki/Computer_security',
    'https://en.wikipedia.org/wiki/Robotics',
    'https://en.wikipedia.org/wiki/Memory_management',
    'https://en.wikipedia.org/wiki/Evolutionary_computation',
    'https://en.wikipedia.org/wiki/J_Sharp',
    'https://livescript.net/',
    'https://en.wikipedia.org/wiki/Modula-3',
    'https://en.wikipedia.org/wiki/Statistical_learning_theory',
    'https://en.wikipedia.org/wiki/REST',
    'https://en.wikipedia.org/wiki/Synchronization_(computer_science)',
    'https://en.wikipedia.org/wiki/Software_testing',
    'https://ecma-international.org/',
    'https://en.wikipedia.org/wiki/Greedy_algorithm',
    'https://en.wikipedia.org/wiki/COBOL',
    'https://learn.microsoft.com/en-us/azure/quantum/user-guide/language/', # Q#
    'https://en.wikipedia.org/wiki/Microservices',
    'https://en.wikipedia.org/wiki/Ethical_hacking',
    'https://en.wikipedia.org/wiki/Shell_script',
    'https://octave.org/',
    'https://en.wikipedia.org/wiki/Cryptography',
    'https://www.scala-lang.org/',
    'https://squeak.org/',
    'https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model',
    'http://www.squirrel-lang.org/',
    'https://en.wikipedia.org/wiki/SOAP',
    'https://groovy-lang.org/',
    'https://en.wikipedia.org/wiki/DevOps',
    'https://chapel-lang.org/',
    'https://racket-lang.org/',
    'https://en.wikipedia.org/wiki/Quantum_computing',
    'https://en.wikipedia.org/wiki/MapReduce',
    'https://en.wikipedia.org/wiki/Communication_protocol',
    'https://en.wikipedia.org/wiki/Wireless_network',
    'https://en.wikipedia.org/wiki/Front-end_web_development',
    'https://en.wikipedia.org/wiki/Deep_learning',
    'https://squeak.org/',
    'https://www.scheme.org/',
    'https://www.jsoftware.com/', # J
    'https://www.tcl.tk/',
    'https://en.wikipedia.org/wiki/NoSQL',
    'https://en.wikipedia.org/wiki/ML_(programming_language)',
    'https://en.wikipedia.org/wiki/Data_modeling',
    'https://en.wikipedia.org/wiki/Adobe_ColdFusion',
    'https://ocaml.org/',
    'https://isocpp.org/', # C++
    'https://en.wikipedia.org/wiki/S-PLUS',
    'https://en.wikipedia.org/wiki/Continuous_integration',
    'https://storm.apache.org/',
    'https://www.wolfram.com/language/',
    'https://en.wikipedia.org/wiki/Artificial_intelligence',
    'https://en.wikipedia.org/wiki/Version_control',
    'https://en.wikipedia.org/wiki/ActionScript',
    'https://cassandra.apache.org/',
    'https://en.wikipedia.org/wiki/Computer_vision',
    'https://en.wikipedia.org/wiki/Software_engineering',
    'https://x10-lang.org/',
    'https://www.sas.com/',
    'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    'https://en.wikipedia.org/wiki/Cloud_computing',
    'https://www.ni.com/en-us/shop/labview.html',
    'https://www.stata.com/',
    'https://www.adacore.com/sparkpro',
    'https://en.wikipedia.org/wiki/Service-oriented_architecture',
    'https://www.erlang.org/',
    'https://en.wikipedia.org/wiki/Computer_architecture',
    'https://en.wikipedia.org/wiki/Video_game_development',
    'https://en.wikipedia.org/wiki/Neural_network',
    'https://scratch.mit.edu/',
    'https://soliditylang.org/',
    'https://en.wikipedia.org/wiki/Blockchain',
    'https://clojure.org/',
    'https://www.dyalog.com/', # APL
    'https://boo-lang.github.io/',
    'https://ring-lang.net/',
    'https://hacklang.org/',
    'https://nim-lang.org/',
    'https://learn.microsoft.com/en-us/powershell/',
    'https://iolanguage.org/',
    'https://en.wikipedia.org/wiki/Error_detection_and_correction',
    'https://en.wikipedia.org/wiki/Big_data',
    'https://fortran-lang.org/',
    'https://www.alice.org/',
    'https://en.wikipedia.org/wiki/PL/I',
    'https://en.wikipedia.org/wiki/Data_structure',
    'https://en.wikipedia.org/wiki/Simula',
    'https://en.wikipedia.org/wiki/Concurrency_(computer_science)',
    'https://en.wikipedia.org/wiki/Algorithm',
    'https://www.ibm.com/spss',
    'https://www.cs.arizona.edu/icon/',
    'https://couchdb.apache.org/',
    'https://smlfamily.github.io/',
    'https://en.wikipedia.org/wiki/CAP_theorem',
    'https://www.freepascal.org/',
    'https://en.wikipedia.org/wiki/Augmented_reality',
    'https://en.wikipedia.org/wiki/CI/CD',
    'https://en.wikipedia.org/wiki/PL/SQL',
    'https://www.java.com/',
    'https://projectoberon.net/',
    'https://en.wikipedia.org/wiki/Data_mining',
    'https://en.wikipedia.org/wiki/Finite_automaton',
    'https://en.wikipedia.org/wiki/Computer_graphics',
    'https://en.wikipedia.org/wiki/Natural_language_processing',
    'https://en.wikipedia.org/wiki/Graph_theory',
    'https://developer.apple.com/objective-c/',
    'https://en.wikipedia.org/wiki/ACID',
    'https://en.wikipedia.org/wiki/ZPL_(programming_language)',
    'https://en.wikipedia.org/wiki/Operating_system',
    'https://en.wikipedia.org/wiki/Internet_Protocol',
    'https://en.wikipedia.org/wiki/BCPL',
    'https://en.wikipedia.org/wiki/ABAP',
    'https://www.tug.org/', # TeX
    'https://en.wikipedia.org/wiki/Human%E2%80%93computer_interaction',
    'https://en.wikipedia.org/wiki/AWK',
    'https://en.wikipedia.org/wiki/Delphi_(software)',
    'https://yorick.github.io/'
  ]

  # Connect to the database using the constant from app.rb
  # We use the DB_PATH defined in app.rb to ensure we use the same database
  puts "Using database at: #{DB_PATH}"
  db = SQLite3::Database.new(DB_PATH)
  db.results_as_hash = true

  urls_to_scrape.each do |url|
    begin
      puts "Scraping #{url}..."
      # Open the URL
      html = URI.open(url)
      doc = Nokogiri::HTML(html)

      # Extract title
      title = doc.title || url

      # Extract text from body, removing scripts and styles for cleaner content
      doc.css('script, style').remove
      content = doc.at('body')&.text&.strip&.gsub(/\s+/, ' ') || ""

      # Check if the page already exists to avoid duplicates
      existing = db.execute("SELECT url FROM pages WHERE url = ?", url).first

      if existing
        puts "Updating existing record for #{url}"
        db.execute("UPDATE pages SET title = ?, content = ?, language = 'en' WHERE url = ?", [title, content, url])
      else
        puts "Inserting new record for #{url}"
        db.execute("INSERT INTO pages (url, title, content, language) VALUES (?, ?, ?, 'en')", [url, title, content])
      end

    rescue OpenURI::HTTPError => e
      puts "Failed to fetch #{url}: #{e.message}"
    rescue => e
      puts "Error processing #{url}: #{e.message}"
    end
  end

  db.close
  puts "Scrape complete."
end
