# Gemfile
source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'sqlite3', '~> 1.6'
gem 'json' # For handling JSON responses
# For development, we can add a reloader
gem 'sinatra-contrib', require: 'sinatra/reloader'