name: Lint

on:
  push

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    name: Run Super-Linter 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter 
        uses: super-linter/super-linter@v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false    # Hvis du kun vil scanne ændrede filer
          
          # Aktiverer relevante lintere
          VALIDATE_RUBY: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MARKDOWN: true     
          VALIDATE_YAML: true    
          VALIDATE_YAML_YAMLLINT: true  # bruger så yamllint i stedet for prettier


           # Sørger for at vi ser de faktiske fejl i loggen
          LOG_LEVEL: DEBUG
          OUTPUT_DETAILS: detailed
          OUTPUT_FORMAT: tap
          PRINT_ALPACA: false     # (Skjul ASCII-logo så loggen er ren)
          ANNOTATIONS: true     # Gør at GitHub viser fejl som annotations i UI ved PR
          