name: Ruby Linter

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Sets up a Ruby environment and installs your project's dependencies
      - name: Set up Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Or the Ruby version you are using
          bundler-cache: true # Automatically runs 'bundle install'
          working-directory: ./new_app_ruby # <-- ADD THIS: Tell bundler where to find the Gemfile

      # 3. Runs the Standard linter
      - name: Run StandardRB Linter
        working-directory: ./new_app_ruby # <-- ADD THIS: Run the linter in the correct directory
        run: bundle exec standard