name: Automated local API tests using Postman CLI

on: 
  push:
     branches: [featureSmoketestPostman]

jobs:
  automated-local-api-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: new_app_ruby

    steps:
      # Tjek koden ud
      - uses: actions/checkout@v4

      - name: List repo structure
        run: |
          pwd
          ls -al
          echo "--- new_app_ruby ---"
          ls -al new_app_ruby

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libsqlite3-0 libsqlite3-dev ca-certificates curl

      - name: Install gems
        run: bundle install

      - name: Debug Ruby environment
        run: |
         ruby -v
         which ruby
         bundle list

      # Start app’en i baggrunden
      - name: Start app
        run: |
          nohup bundle exec ruby app.rb > app.log 2>&1 &
          echo "Waiting for API..."
          for i in {1..30}; do
            if curl -sSf http://localhost:8080 > /dev/null; then
              echo "App is up!"
              break
            fi
            echo "Still waiting..."
            sleep 2
          done
          if [ "$success" = false ]; then
            echo "❌ App failed to start on port 8080"
            exit 1
          fi

      # Debug step
      - name: Show app log if startup fails
        if: always()
        run: cat new_app_ruby/app.log

      # Installer Postman CLI
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # Log ind i Postman
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Kør smoketests mod localhost
      - name: Run Postman smoketests
        run: |
          postman collection run "41748160-a6d7dfee-dc2a-4d14-84d5-fadf82b490a1" \
            --env-var baseUrl="http://localhost:8080" \
            --bail \
            --reporters cli,junit \
            --reporter-junit-export postman-results.xml

      # 8. Upload rapport
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: postman-results
          path: new_app_ruby/postman-results.xml