name: Rubocop

on:
  push:
    branches: [ "main", "dev", "linter-feature" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 23 * * 1' # hver mandag kl 23:18 UTC

jobs:
  rubocop:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install dependencies
        working-directory: new_app_ruby
        run: bundle install

      - name: Rubocop run
        working-directory: new_app_ruby
        run: |
          bundle exec rubocop --require code_scanning \
            --format CodeScanning::SarifFormatter \
            -o ../rubocop.sarif || true

      - name: Upload Sarif output
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rubocop.sarif
          token: ${{ secrets.MY_PAT }}
